// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgRVzzN8uGeyH9bu7QVtaQhb60V4-lSUc',
    appId: '1:357286750704:web:83789d3c0aa6550c645535',
    messagingSenderId: '357286750704',
    projectId: 'ennodanoteuh',
    authDomain: 'ennodanoteuh.firebaseapp.com',
    storageBucket: 'ennodanoteuh.appspot.com',
    measurementId: 'G-DNX2XH33J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCerLTbzbf4EajQ5NksGldzf-h02bQQP3c',
    appId: '1:357286750704:android:6b97ca07bf528e0c645535',
    messagingSenderId: '357286750704',
    projectId: 'ennodanoteuh',
    storageBucket: 'ennodanoteuh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC_J2U1_SqvyIHqbXe7KWW1KOHuDQRLOg',
    appId: '1:357286750704:ios:24d614c5149c6771645535',
    messagingSenderId: '357286750704',
    projectId: 'ennodanoteuh',
    storageBucket: 'ennodanoteuh.appspot.com',
    iosClientId:
        '357286750704-7d4asc5euoela97vsn5bti0fcej7qtad.apps.googleusercontent.com',
    iosBundleId: 'in.exrockstar.ennodanoteuh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC_J2U1_SqvyIHqbXe7KWW1KOHuDQRLOg',
    appId: '1:357286750704:ios:24d614c5149c6771645535',
    messagingSenderId: '357286750704',
    projectId: 'ennodanoteuh',
    storageBucket: 'ennodanoteuh.appspot.com',
    iosClientId:
        '357286750704-7d4asc5euoela97vsn5bti0fcej7qtad.apps.googleusercontent.com',
    iosBundleId: 'in.exrockstar.ennodanoteuh',
  );
}
